services:
  postgres:
    image: postgres:16
    container_name: harbor_postgres
    environment:
      POSTGRES_USER: harbor
      POSTGRES_PASSWORD: harbor123
      POSTGRES_DB: harbor_manufatura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
